/*
* generated by Xtext
*/
package de.pellepelster.myadmin.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyAdminDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.pellepelster.myadmin.dsl.ui.internal.MyAdminDslActivator.getInstance().getInjector("de.pellepelster.myadmin.dsl.MyAdminDsl");
	}
	
}
